# Prerequisites

In [222]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [223]:
# importing numpy module
import numpy as np

In [224]:
# working with lists nad maxtrixes
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Reshaping 

In [225]:
# reshaping the dimantions of 'a'
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [226]:
# reshaping the dimantions of 'a'
# value '-1' is the any value which is needed to create matrixes with given shape
a.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [227]:
a.reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [228]:
a.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [229]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [230]:
# returns the array, flattened
a.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Getting basic informations about array

In [231]:
# getting information about 'a'
a.shape

(15,)

In [232]:
# as you can see, the shape of 'a' is countig from the first inicialization of 'a' - "a = np.arange(15)"
# ! if you wanna work on changing value 'a' you have to assign this function to 'a' and execute one more time shape method

In [233]:
# assign value to 'a'
a = a.reshape(5,3)

In [234]:
a.shape

(5, 3)

In [235]:
# now everything is working fine, so now we are ready to know another methods

In [236]:
# the number of axes (dimensions) of the array.
a.ndim

2

In [237]:
# an object describing the type of the elements in the array. One can create or specify dtype’s using 
# standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 
# are some examples.
a.dtype

dtype('int64')

In [238]:
# name of type
a.dtype.name

'int64'

In [239]:
# the total number of elements of the array, working like len() method
a.size

15

In [240]:
# the size in bytes of each element of the array. For example, an array of elements of type float64 has 
# itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to 
# ndarray.dtype.itemsize.
a.itemsize

8

In [241]:
# the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute 
# because we will access the elements in an array using indexing facilities.
a.data

# Array Creation

In [242]:
# creating list by getting values
b_vector_by_values = np.array([2, 3, 4])
print(b_vector_by_values)

[2 3 4]


In [243]:
# creating list by existing list
# clasic python list
classic_list = [2, 3, 4]
b_vector_by_list = np.array(classic_list)
print(b_vector_by_list)

[2 3 4]


In [244]:
# creating list by getting values
# clasic python maxtrix which is created by list of lists
b_matrix_by_values = np.array([[1, 2, 3],[4, 5, 6]])
print(b_matrix_by_values)

[[1 2 3]
 [4 5 6]]


In [245]:
classic_maxtrix = [[1, 2, 3],[4, 5, 6]]
b_matrix_by_matrix = np.array(classic_maxtrix) 
print(b_matrix_by_matrix)

[[1 2 3]
 [4 5 6]]


In [246]:
# another way to array creation
# The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the 
# function empty creates an array whose initial content is random and depends on the state of the memory. 
# By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [247]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [248]:
np.empty((2, 3))

array([[9., 7., 5.],
       [2., 5., 4.]])

In [249]:
# linespace(start_value, end_value, number_of_elements_in_list)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### Fastback to logic in python -  difference between '==' and 'is'
#### As you've already known python has two different tools for checking equals of values, ' '==' and 'is'. 
##### The first one '==' is more common and allows checking if two values its the same..
##### The second one check also it's the two values are the same by checking the space in the memory disk..

In [250]:
# creating two normal list
fastback_a = [2, 3, 4]
fastback_b = [2, 3, 4]

In [251]:
print(fastback_a)
print(fastback_b)
print(fastback_a == fastback_b)

[2, 3, 4]
[2, 3, 4]
True


In [252]:
print(fastback_a is fastback_b)
print(hex(id(fastback_a)))
print(hex(id(fastback_b)))

False
0x7f63c9317cc0
0x7f63c93835c0


In [253]:
# so as you can see, the results from these two methods are difference, because '=='
# checking only equals of values, but 'is' also check space of memory where the value is saved

# Basic Operations

In [254]:
a = np.array([20, 30, 40, 50])
b = np.arange(4) # [0, 1, 2, 3]
print(a - b)

[20 29 38 47]


In [255]:
print(b**2)

[0 1 4 9]


In [256]:
# Field of the triangle, values of the base is from list 'a' and height is 10
# REMEMBER we didn't assign  previous step to 'b' so b is still [0, 1, 2, 3]
print( 10 * b / 2)

[ 0.  5. 10. 15.]


In [257]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A -B)

[[-1  1]
 [-3 -3]]


In [258]:
# elementwise product
print(A * B)

[[2 0]
 [0 4]]


In [259]:
# matrix product
print(A @ B)

[[5 4]
 [3 4]]


# Indexing, Slicing and Iterating

In [260]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [261]:
print(a[2])

8


In [262]:
print(a[2:5])

[ 8 27 64]


In [263]:
# from start to position 6, exclusive, get every 2nd element
print(a[:6:2])

[ 0  8 64]


In [264]:
print(a[::-1])

[729 512 343 216 125  64  27   8   1   0]


In [265]:
# a 2D array
b = np.arange(45).reshape(9,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [266]:
print(b[2, 3])

13


In [267]:
# each row in the second column of b
print(b[0:5, 1])

[ 1  6 11 16 21]


In [268]:
# equivalent to the previous example
print(b[:, 1])

[ 1  6 11 16 21 26 31 36 41]


In [269]:
# each column in the second and third row of b
print(b[1:3, :])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [270]:
# the last row. Equivalent to b[-1, :]
print(b[-1])

[40 41 42 43 44]


In [271]:
# a 3D array (two stacked 2D arrays)
c = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]


In [272]:
# number of dimensions
c.ndim

3

In [273]:
# same as c[1, :, :] or c[1]
print(c[1, ...])

[[100 101 102]
 [110 112 113]]


In [274]:
# same as c[:, :, 2]
print(c[..., 2])

[[  2  13]
 [102 113]]


In [275]:
d = np.arange(12).reshape(3, 4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [276]:
# first dim selection and second dim selection
b1 = np.array([False, True, True])         
b2 = np.array([True, False, True, False])  

In [277]:
# selecting rows - first row is skipped becasue the first value from b1 is False
print(d[b1, :])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [278]:
# selecting columns - first and thitd column 
print(d[:, b2])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [279]:
# wierd..  
print(d[b1, b2])  

[ 4 10]


# Stacking together different arrays

In [280]:
# 'rg' is needed to create array with randoms values
rg = np.random.default_rng(1)

In [281]:
e = np.floor(10 * rg.random((2, 12)))
print(e)

[[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]
 [3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]]


In [282]:
# split `e` into 3 vsplit method also exists
print(np.hsplit(e, 3))

[array([[5., 9., 1., 9.],
       [3., 7., 3., 4.]]), array([[3., 4., 8., 4.],
       [1., 4., 2., 2.]]), array([[5., 0., 7., 5.],
       [7., 2., 4., 9.]])]


In [283]:
# get first array from the spilted 'e' which was spited into 3
print(np.hsplit(e, 3)[0])

[[5. 9. 1. 9.]
 [3. 7. 3. 4.]]


In [284]:
# split `a` after the third and the fourth column
print(np.hsplit(e, (3, 4)))

[array([[5., 9., 1.],
       [3., 7., 3.]]), array([[9.],
       [4.]]), array([[3., 4., 8., 4., 5., 0., 7., 5.],
       [1., 4., 2., 2., 7., 2., 4., 9.]])]


# Copies and Views
#### Fastback tone more to difference between '==' and 'is'

In [285]:
f = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [286]:
# no new object is created, only values from 'f' is saved to 'g'. So the sapce in memeory is the same for both varaibles
g = f
print('g: '+ hex(id(g)))
print('f: '+ hex(id(f)))
print(g is f)

g: 0x7f63c930c990
f: 0x7f63c930c990
True


In [287]:
# now 'g' is a view of 'f'. So the space in memory is difference for both variables, BUT 'g' is still connect 
# to 'f', we can check this by base method which return base of array
g = f.view()
print('g: '+ hex(id(g)))
print('f: '+ hex(id(f)))
print('Is the same space in memory for both values?', g is f)
print('Is \'g\' based on \'f\'?', g.base is f)

g: 0x7f63c92a55d0
f: 0x7f63c930c990
Is the same space in memory for both values? False
Is 'g' based on 'f'? True


In [288]:
# finally new object is created
g = f.copy()
print('g: '+ hex(id(g)))
print('f: '+ hex(id(f)))
print('Is the same space in memory for both values?', g is f)
print('Is \'g\' based on \'f\'?', g.base is f)

g: 0x7f63c9314450
f: 0x7f63c930c990
Is the same space in memory for both values? False
Is 'g' based on 'f'? False
